code/films/urls.py
"""定义learning_logs的URL模式"""

from django.urls import path, re_path
from django.conf.urls.static import static
from django.conf import settings

from . import views


# 命名空间
app_name = 'films'


# 注意path于re_path的用法区别
# path 用于不含参数方法的URL映射
# re_path 用于含参数方法的URL映射

urlpatterns = [
	# 显示所有的主题
	path('index/', views.index, name='index'),

	path('like/', views.like, name='like'),

	re_path('single/(?P<film_id>\d+)/', views.single, name='single'),
	re_path('comment/(?P<film_id>\d+)/', views.comment, name='comment'),
	re_path('movie/(?P<film_id>\d+)/', views.movie, name='movie'),

	path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('quit/', views.quit, name='quit'),
    path('person/', views.person, name='person')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

code/imagination/urls.py
"""定义learning_logs的URL模式"""

from django.urls import path, re_path
# from django.views.decorators.csrf import csrf_exempt

from . import views

# 命名空间
app_name = 'imagination'


# 注意path于re_path的用法区别
# path 用于不含参数方法的URL映射
# re_path 用于含参数方法的URL映射

urlpatterns = [
    # 小工具首页
	path('showIndex/', views.showIndex, name='showIndex'),
	# 学校入口页面
	path('collegeEntry/', views.collegeEntry, name='collegeEntry'),
	# 学校信息页面
	path('collegeInfo/', views.collegeInfo, name='collegeInfo'),
	path('academyInfo/', views.academyInfo, name='academyInfo'),
	path('majorInfo/', views.majorInfo, name='majorInfo'),
	path('gradeInfo/', views.gradeInfo, name='gradeInfo'),
	path('classInfo/', views.classInfo, name='classInfo'),
	re_path('studentInfo/(?P<student_id>\d+)/', views.studentInfo, name='studentInfo'),
	re_path('teacherInfo/(?P<teacher_id>\d+)/', views.teacherInfo, name='teacherInfo'),
]

code/learning_logs/urls.py
"""定义learning_logs的URL模式"""

from django.urls import path, re_path


from . import views

# 命名空间
app_name = 'learning_logs'


# 注意path于re_path的用法区别
# path 用于不含参数方法的URL映射
# re_path 用于含参数方法的URL映射

urlpatterns = [
	# 显示所有的主题
	path('topics/', views.topics, name='topics'),

	# 显示指定主题的细节
	re_path('topic/(?P<topic_id>\d+)/', views.topic, name='topic'),

	# 用于添加新主题的网页
	path('new_topic/', views.new_topic, name='new_topic'),

	# 用于添加新条目的页面
	re_path('new_entry/(?P<topic_id>\d+)/', views.new_entry, name='new_entry'),

	# 用于编辑条目的页面
	re_path('edit_entry/(?P<entry_id>\d+)/', views.edit_entry, name='edit_entry'),
]

code/selfsearching/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('admin_app.urls', namespace='admin_app')),
    path('', include('users.urls', namespace='users')),
    path('', include('learning_logs.urls', namespace='learning_logs')),
    path('', include('small_tools.urls', namespace='small_tools')),
    path('', include('imagination.urls', namespace='imagination')),
    path('', include('films.urls', namespace='films')),
]

code/small_tools/urls.py
"""定义learning_logs的URL模式"""

from django.urls import path, re_path
from django.views.decorators.csrf import csrf_exempt

from . import views

# 命名空间
app_name = 'small_tools'


# 注意path于re_path的用法区别
# path 用于不含参数方法的URL映射
# re_path 用于含参数方法的URL映射

urlpatterns = [
    # 小工具首页
	path('showTools/', views.showTools, name='showTools'),

    # snmp mib代码自动生成工具
	path('mibToCode/', views.mibToCode, name='mibToCode'),

	# 字符串处理算法页面
	path('algoString/', views.algoString, name='algoString'),

	# 正则表达式学习页面
	path('algoRegix/', csrf_exempt(views.algoRegix), name='algoRegix'),
]

code/users/urls.py
"""为应用程序users定义URL模式"""

from django.urls import path
from django.contrib.auth.views import login

from . import views


app_name = 'users'

urlpatterns = [
	#登录页面
	path('login/', login, {'template_name': 'users/login.html'}, name='login'),
		
	#注销
	path('logout/', views.logout_view, name='logout'),
	
	#注册
	path('register/', views.register, name='register'),
]

code/films/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
@Author  : Leo
@Connect : lipf0627@163.com
@File    : forms.py
@site    :
@Time    : 2018/11/21 23:03
@Software: PyCharm Community Edition
"""

from django import forms
from .models import Film
from django.forms import widgets


class FilmForm(forms.Form):
	"""大学表单"""
	# class Meta:
	# 	model = Film
	# 	fields = ['name', 'description']
	# 	labels = {'description': ''}
	name = forms.CharField(max_length=50)
	id = forms.CharField(max_length=100)
	description = forms.CharField(max_length=500)
	date_added = forms.DateField()

code/films/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.http import JsonResponse
from django.contrib.auth.hashers import make_password, check_password
from django.db import models

from .models import Movie, User, Comment, Advertise

# Create your views here.
# 首页
def index(request):
    # return HttpResponse('hi')
    # return render(request, 'index.html')

    # print(request.session.items())
    # print(request.COOKIES)
    user_id = int(request.session.get('_auth_user_id'))
    # print('user_id = %s' % user_id)
    user = User.objects.get(id=user_id)
    # print(user.username)

    # 导航显示的视频封面图片
    carousel_list = Movie.objects.filter(is_carousel=True)
    for i in carousel_list:
        i.new_link = 'https://img3.doubanio.com/view/photo/l/public/' + str(i.cover_link).split('_')[0] + '.webp'
        if i.new_link.count('.webp') > 1:
            i.new_link = i.new_link[ : len(i.new_link) - 5]
#        print(i.new_link)

    # 推荐页面显示的视频小图（10个）
    recommend_list = Movie.objects.order_by('-mark')[:10]
    for r in recommend_list:
        r.pic_link = 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/' + str(r.cover_link).split('_')[0] + '.webp'
        if r.pic_link.count('.webp') > 1:
            r.pic_link = r.pic_link[ : len(r.pic_link) - 5]
        # print(r.pic_link)
        r.like_count = len(r.like.all())  # 视频被收藏的总数
        # print(r.like_count)

    return render(request, 'films/index.html', {'carousel_list': carousel_list,
                                          'recommend_list': recommend_list,
                                          'username': user.username,
                                        })


# 收藏/取消收藏
def like(request):
    state = request.GET.get('state')  # 收藏状态
    movie_id = request.GET.get('movie_id')  # 视频id

    token = request.COOKIES.get('userToken')
    currentuser = User.objects.get(token=token)  # 当前登陆的用户

    like_movie = Movie.objects.get(id=movie_id)  # 获取视频对象
    # print(like_movie.like.all())  # 该视频对应的所有收藏用户

    if state == '1':  # 取消
        like_movie.like.remove(currentuser)
    elif state == '0':  # 收藏
        like_movie.like.add(currentuser)

    return JsonResponse({'data':'success'})


# 详情页
def single(request, mid):
    key = request.COOKIES.get('usernameKey')
    usernameKey = request.session.get(key, 0)

    token = request.COOKIES.get('userToken')

    single_movie = Movie.objects.get(id=mid)

    try:
        currentuser = User.objects.get(token=token)
    except User.DoesNotExist as e:
        currentuser = None

    # print(single_movie.like.all())  # 返回当前电影对应的收藏用户名称
    if currentuser != None:  # 当前用户已登陆
        if currentuser in single_movie.like.all():  # 当前登陆用户已经收藏了本电影
            is_like = 1
        else:  # 当前用户没有收藏此电影
            is_like = 0
    else:
        is_like = 3

    single_movie.single_link = 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/' + \
                               str(single_movie.cover_link).split('_')[0] + '.webp'
    if single_movie.single_link.count('.webp') > 1:
        single_movie.single_link = single_movie.single_link[: len(single_movie.single_link) - 5]

    # 侧边栏推荐
    side_recommend = Movie.objects.order_by('-mark')[ : 3]
    for s in side_recommend:
        s.new_link = 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/' + str(s.cover_link).split('_')[0] + '.webp'
        if s.new_link.count('.webp') > 1:
            s.new_link = s.new_link[ : len(s.new_link) - 5]

        s.like_count = len(s.like.all())


    # 获取评论
    try:
        comment_list = Comment.objects.filter(movie_id=mid)
    except Comment.DoesNotExist as e:
        comment_list = []
    comment_list_count = len(comment_list)  # 评论总数

    return render(request, 'single.html', {'movie':single_movie,
                                           'side_recommend':side_recommend,
                                           'username':usernameKey,
                                           'is_like':is_like,
                                           'comment_list':comment_list,
                                           'comment_list_count':comment_list_count,
                                           })


# 评论
def comment(request, mid):
    comment_content = request.POST.get('comment')

    token = request.COOKIES.get('userToken')
    currentuser = User.objects.get(token=token)
    m = Movie.objects.get(id=mid)

    Comment.objects.create(comment_content=comment_content, movie_id=m, user_id=currentuser)

    return redirect('/single/' + mid)


# 各类视频展示及搜索页面
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
def movie(request, tid):
    key = request.COOKIES.get('usernameKey')
    usernameKey = request.session.get(key, 0)

    # search_result_list = Movie.objects.filter(style_type=)
    # 根据id,分类搜索
    # print(tid)
    # print(type(tid))
    if tid == '2':  # 最新
        search_list = Movie.objects.order_by('-release_time')
    elif tid == '4':  # 高分
        search_list = Movie.objects.order_by('-mark')
    elif tid == '5':  # 华语
        search_list = Movie.objects.filter(country_id=3)
    elif tid == '6':  # 欧美
        search_list = Movie.objects.filter(country_id=2)
    elif tid == '7':  # 韩国
        search_list = Movie.objects.filter(country_id=1)
    elif tid == '8':  # 日本
        search_list = Movie.objects.filter(country_id=4)
    elif tid == '9':  # 更多
        search_list = Movie.objects.all()
    elif tid == '0':
        key_word = request.POST.get('keyword')
        search_list = Movie.objects.filter(name__contains=key_word)


    # 重新拼接处理封面图片的url以及出演人员的处理（默认显示3个主角）
    for s in search_list:
        # 封面图片的链接
        s.slink = 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/' + str(s.cover_link).split('_')[0] + '.webp'
        if s.slink.count('.webp') > 1:
            s.slink = s.slink[ : len(s.slink) - 5]
        # print(s.slink)

        # 主角
        s.s_lead = s.lead_role.all()[:3]
        # print(s.s_lead)

        s.like_count = len(s.like.all())  # 视频被收藏的总数


    paginator = Paginator(search_list, 6) # 一页显示 6 条
    page = request.GET.get('page')

        # 获取对应页面
    try:
        results = paginator.page(page)

        # 页面不是整数，返回第一页
    except PageNotAnInteger:
        results = paginator.page(1)

        # 页码越界，返回最后一页
    except EmptyPage:
        results = paginator.page(paginator.num_pages)

    # 侧边栏推荐
    side_recommend = Movie.objects.order_by('-mark')[: 3]
    for s in side_recommend:
        s.new_link = 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/' + str(s.cover_link).split('_')[
            0] + '.webp'
        if s.new_link.count('.webp') > 1:
            s.new_link = s.new_link[: len(s.new_link) - 5]

        s.like_count = len(s.like.all())

    # 底部广告栏
    ad_list = Advertise.objects.all()
    import os
    for a in ad_list:
        print(a.pic)


    return render(request, 'movie.html', {'username':usernameKey,
                                          'results':results,
                                          'side_recommend':side_recommend,
                                          'ad_list':ad_list,
                                          })


# 登陆页
def login(request):
    # 将上一个页面的地址记录
    url = request.META.get('HTTP_REFERER', '/   ')
    print(url)
    request.session['preUrl'] = url
    if request.method == 'GET':
        return render(request, 'login.html')
    else:
        nickname = request.POST.get('nickname')
        password = request.POST.get('password')

        # 查询用户是否存在
        try:
            u = User.objects.get(username=nickname)
        except User.DoesNotExist as e:
            return redirect('/login/')

        # 如果存在,验证密码是否正确
        if password != u.password:
            return redirect('/login/')

        # 登陆成功
        response = HttpResponseRedirect('/index/')
        token = make_password(nickname)
        u.token = token
        u.save()
        response.set_cookie('userToken', token)

        request.session['username'] = u.username
        response.set_cookie('usernameKey', 'username')

        return response


# 注册页
def register(request):
    if request.method == 'GET':
        return render(request, 'register.html')
    else:
        # 如果是ajax请求
        if request.is_ajax():
            # 验证账号是否存在
            nickname = request.POST.get('nickname')

            try:
                user = User.objects.get(username=nickname)
                # 说明账号已被使用
                return JsonResponse({'data':'1'})
            except User.DoesNotExist as e:
                # 判断邮箱是否可用
                email = request.POST.get('email')
                try:
                    email_user = User.objects.get(email=email)
                    # 说明邮箱已被占用
                    return JsonResponse({'data':'2'})
                except User.DoesNotExist as e:
                    # 邮箱可用
                    return JsonResponse({'data':'3'})
                # 说明账号可以使用
                return JsonResponse({'data':'0'})

        # 如果信息验证全部通过,注册用户
        else:
            nickname = request.POST.get('nickname')
            email = request.POST.get('email')
            password = request.POST.get('password')
            subscribe = request.POST.get('subscribe')

            # 用户token
            userToken = make_password(nickname)

            # 创建用户
            user = User.createuser(username=nickname, password=password, email=email, is_subscribe=subscribe, token=userToken)
            user.save()

            # 注册成功需要做状态保持,写入session,默认登陆
            request.session['username'] = nickname
            response = redirect('/index/')
            response.set_cookie('usernameKey', 'username')
            response.set_cookie('userToken', userToken)

            return response


# 退出页
from django.contrib.auth import logout
def quit(request):
    logout(request)
    return redirect('/index/')


# 个人中心
def person(request):
    key = request.COOKIES.get('usernameKey')

code/films/templates/films/base.html
{% load static from staticfiles %}

<!--加上该行，页面样式会消失-->
<!--<!DOCTYPE HTML>-->

<html>
<head>
    <title>See视频</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="keywords" content="Movie_store Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design"/>
    <script type="application/x-javascript"> addEventListener("load", function () {
        setTimeout(hideURLbar, 0);
    }, false);

    function hideURLbar() {
        window.scrollTo(0, 1);
    } </script>
    <link href="{% static 'css/bootstrap.css' %}" rel='stylesheet' type='text/css'/>
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" media="all"/>
    <!-- start plugins -->
    <script type="text/javascript" src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
<!--{#    <link href='http://fonts.useso.com/css?family=Roboto+Condensed:100,200,300,400,500,600,700,800,900' rel='stylesheet'#}-->
<!--{#          type='text/css'>#}-->

    <!--css-->
    {% block styles %}
    {% endblock %}





    <script src="{% static 'js/responsiveslides.min.js' %}"></script>
    <script>
        $(function () {
            $("#slider").responsiveSlides({
                auto: true,
                nav: true,
                speed: 500,
                namespace: "callbacks",
                pager: true,
            });
        });
    </script>

        <!--js-->
    {% block scripts %}
    {% endblock %}

</head>
<body>

<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
    <div class="container">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"
                data-toggle="collapse" data-target="#navbar"
                aria-expanded="false" aria-controls="navbar">
            </button>
            <a class="navbar-brand" href="{% url 'admin_app:index' %}">Home</a>
        </div>

        <div id="navbar" class="navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'imagination:showIndex' %}">Imagination</a></li>
            </ul>

            <ul class="nav navbar-nav">
                <li><a href="{% url 'learning_logs:topics' %}">Learning_logs</a></li>
            </ul>

            <ul class="nav navbar-nav">
                <li><a href="{% url 'small_tools:showTools' %}">SmallTools</a></li>
            </ul>

            <ul class="nav navbar-nav">
                <li><a href="{% url 'films:index' %}">Films</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a>Hello, {{ user.username }}.</a></li>
                    <li><a href="{% url 'users:logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
                {% else %}
                    <li><a href="{% url 'users:register' %}"><span class="glyphicon glyphicon-user"></span> Register</a></li>
                    <li><a href="{% url 'users:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                {% endif %}
            </ul>
        </div><!-- /.nav-collapse -->

    </div>
</nav>


<div class="container">
    <div class="container_wrap">
        <div class="header_top">
            <div class="col-sm-3 logo">
                <a href="/index/" style="font-size: 26px; text-decoration: none; color: #D8232A">
{#                    <img src="{% static 'images/logo.png' %}" alt=""/>#}
                    See视频
                </a>
            </div>
            <div class="col-sm-6 nav">
                <ul>
                    <li><span class="simptip-position-bottom simptip-movable" data-tooltip="最新"><a
                            href="/movie/2/">最新 </a> </span></li>
                    <li><span class="simptip-position-bottom simptip-movable" data-tooltip="高分"><a
                            href="/movie/4/">高分 </a></span></li>
                    <li><span class="simptip-position-bottom simptip-movable" data-tooltip="华语"><a
                            href="/movie/5/">华语 </a></span></li>
                    <li><span class="simptip-position-bottom simptip-movable" data-tooltip="欧美"><a
                            href="/movie/6/">欧美 </a></span></li>
                    <li><span class="simptip-position-bottom simptip-movable" data-tooltip="韩国"><a
                            href="/movie/7/">韩国 </a></span></li>
                    <li><span class="simptip-position-bottom simptip-movable" data-tooltip="日本"><a
                            href="/movie/8/">日本 </a></span></li>
                    <li><span class="simptip-position-bottom simptip-movable" data-tooltip="更多"><a
                            href="/movie/9/">更多 </a></span></li>
                </ul>
            </div>
            <div class="col-sm-3 header_right">
                <ul class="header_right_box">
                    {% block mine %}

                    {% endblock %}

                    <div class="clearfix"></div>
                </ul>
            </div>
            <div class="clearfix"></div>
        </div>

{#        轮播图#}
        {% block coverpic %}
        {% endblock %}


        {% block content %}
        {% endblock %}
    </div>
</div>

<div class="container">
    <footer id="footer">
        <div id="footer-3d">
            <div class="gp-container">
                <span class="first-widget-bend"></span>
            </div>
        </div>
        <div id="footer-widgets" class="gp-footer-larger-first-col">
            <div class="gp-container">
                <div class="footer-widget footer-1">
                    <div class="wpb_wrapper">
{#                        <img src="{% static 'images/f_logo.png' %}" alt=""/>#}
                        <span style="font-size: 26px">See视频</span>
                    </div>
                    <br>
                    <p>我还不够完美</p>
                    <p class="text">所以需要继续努力</p>
                </div>
                <div class="footer_box">
                    <div class="col_1_of_3 span_1_of_3">
                        <h3>友链</h3>
                        <ul class="first">
                            <li><a href="http://blackkitty.org/">- BLACKKITTY</a></li>
                        </ul>
                    </div>
                    <div class="col_1_of_3 span_1_of_3">
                        <h3>关于Leo</h3>
                        <ul class="first">
                            <li><a href="#">- 联盟</a></li>
                            <li><a href="#">- 猫</a></li>
{#                            <li><a href="#">Specials</a></li>#}
                        </ul>
                    </div>
                    <div class="col_1_of_3 span_1_of_3">
                        <h3>联系我</h3>
                        <ul class="first">
                            <li><a href="http://web2.qq.com/">- Q &nbsp;&nbsp;2257798128</a></li>
                            <li><a href="#">- E &nbsp;&nbsp;lipf0627@163.com</a></li>
                        </ul>
                        <div class="copy">
                            <p>Copyright &copy; 2017 <a target="_blank"
                                                                                         href="http://idandan.vip/">Leo的个人简介</a>
                            </p>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </footer>
</div>
</body>
</html>

code/films/templates/films/film.html
{% extends 'admin_app/base.html' %}

{% block header %}
	<h2>{{ Film }}</h2>
{% endblock header %}

{% block content %}
	<p>
		<a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
	</p>
	<video controls="controls">
		<source src="images/Safe And Sound--音悦Tai.mp4" type="video/mp4" />
	</video>
	
{% endblock content %}

code/films/templates/films/index.html
{% extends 'films/base.html' %}
{% load static %}


{% block coverpic %}
    <div class="slider">
            <div class="callbacks_container">
                <ul class="rslides" id="slider">
                {% for carousel in carousel_list %}
                    <li><a href="/single/{{ carousel.id }}/"><img src="{{ carousel.new_link }}" class="img-responsive" alt="" style="width: 1140px; height: 475px"/></a>
                        <div class="button">
                            <a href="/single/{{ carousel.id }}/" class="hvr-shutter-out-horizontal">详情</a>
                        </div>
                    </li>
                {% empty %}
                    <li><p>no films</p></li>
                {% endfor %}
                </ul>
            </div>
        </div>
{% endblock %}

{% block mine %}
    <li style="list-style-type: none"><img src="{% static 'images/p1.png' %}" alt=""/></li>
    {% if username %}
        <li style="list-style-type: none"><p><a href="/person/">{{ username }}</a></p></li>
        <li style="list-style-type: none"><p><a href="/quit/">退出</a></p></li>
    {% else %}
        <li style="list-style-type: none"><p><a href="/login/">立即登陆</a></p></li>
    {% endif %}

{% endblock %}

{% block content%}
   <div class="content">
            <div class="box_1">
                <h1 class="m_2">推荐</h1>
                <div class="search">
                    <form method="post" action="/movie/0/">
                        <input type="text" value="搜索..." onFocus="this.value='';"
                               onBlur="if (this.value == '') {this.value ='';}" name="keyword">
                        <input type="submit" value="">
                    </form>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="box_2">


                {% for recommend in recommend_list %}
                    <div class="col-md-2 grid_6">
                        <div class="m_7"><a href="/single/{{ recommend.id }}/"><img style="width: 181px; height: 166px" src="{{ recommend.pic_link }}" class="img-responsive"
                                                                    alt=""/></a></div>
                        <div class="caption1">
                            <ul class="list_5">
                                <li><i class="icon5"> </i>
                                    <p>{{ recommend.like_count }}</p></li>
                            </ul>
                            <!--<i class="icon4 icon6"> </i>-->
                            <a href="/single/{{ recommend.id }}/"><p class="m_3">{{ recommend.name }}</p></a>
                        </div>
                    </div>
                {% empty %}
                    <li><p>no films</p></li>
                {% endfor %}
                <div class="clearfix"></div>
            </div>
        </div>
{% endblock %}

code/films/templates/films/login.html
{% extends 'films/base.html' %}
{% load static %}

{% block content %}
    <div class="content">
        <div class="register">
            <div class="col-md-6 login-left">
                <h3>新用户</h3>
                <p>通过注册一个账号，可以方便的体验网站的更多功能。</p>
                <a class="acount-btn" href="/register/">我要注册</a>
            </div>
            <div class="col-md-6 login-right">
                <h3>登陆</h3>
                <p>已有账号，直接登陆。</p>
                <form method="post" action="/login/">
                    <div>
                        <span>用户名<label>*</label></span>
                        <input type="text" name="nickname">
                    </div>
                    <div>
                        <span>密码<label>*</label></span>
                        <input type="password" name="password">
                    </div>
                    <a class="forgot" href="#">忘记密码?</a>
                    <input type="submit" value="立即登陆">
                </form>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
{% endblock %}

code/films/templates/films/register.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/register.css' %}">
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/register.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="content">
            <div class="register">
                <form method="post" action="/register/">
                    {% csrf_token %}
                    <div class="register-top-grid">
                        <h3>个人信息</h3>
                        <div>
                            <span>昵称<label>*</label></span>
                            <input type="text" name="nickname" id="nickname">
                            <div class="alert alert-info" role="alert" id="nickerror1" style="width: 499px">昵称格式输入错误</div>
                            <div class="alert alert-info" role="alert" id="nickerror2" style="width: 499px">昵称已被占用，请重新输入</div>
                        </div>
                        <div>
                            <span>邮箱<label>*</label></span>
                            <input type="text" name="email" id="email">
                            <div class="alert alert-info" role="alert" id="emailerror1" style="width: 499px">邮箱格式输入错误</div>
                            <div class="alert alert-info" role="alert" id="emailerror2" style="width: 499px">邮箱已被占用，请重新输入</div>
                        </div>
                        <div class="clearfix"></div>
                        <a class="news-letter" href="#">
                            <label class="checkbox"><input type="checkbox" name="subscribe" checked=""><i> </i>订阅电子杂志</label>
                        </a>
                    </div>
                    <div class="register-bottom-grid">
                        <h3>登陆信息</h3>
                        <div>
                            <span>密码<label>*</label></span>
                            <input type="password" name="password" id="password" placeholder="密码长度为6~16个字符">
                            <div class="alert alert-info" role="alert" id="passworderror1" style="width: 499px">密码格式输入错误</div>
                        </div>
                        <div>
                            <span>确认密码<label>*</label></span>
                            <input type="password" name="repassword" id="repassword" placeholder="密码长度为6~16个字符">
                            <div class="alert alert-info" role="alert" id="passworderror2" style="width: 499px">两次密码输入不同</div>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="clearfix"></div>
                    <div class="register-but">
                            <input type="submit" value="立即注册" class="sbt" style="background: #df1f26;color: #FFF;font-size: 1em;padding: 7px 20px;border: none;">
                            <div class="clearfix"></div>
                    </div>
                </form>

            </div>
        </div>
{% endblock %}

code/films/templates/films/show_film.html
{% extends 'admin_app/base.html' %}

{% block header %}
	<h2>{{ film.name }}</h2>
{% endblock header %}

{% block content %}
	<p>
		{{ film.description }}
	</p>
	<video controls="controls">
		<source src="{{ film.url }}" type="video/mp4" />
	</video>
	
{% endblock content %}