code/films/urls.py
"""定义learning_logs的URL模式"""

from django.urls import path, re_path
from django.conf.urls.static import static
from django.conf import settings

from . import views


# 命名空间
app_name = 'films'


# 注意path于re_path的用法区别
# path 用于不含参数方法的URL映射
# re_path 用于含参数方法的URL映射

urlpatterns = [
	# 显示所有的主题
	path('index/', views.index, name='index'),

	path('like/', views.like, name='like'),

	re_path('single/(?P<film_id>\d+)/', views.single, name='single'),
	re_path('comment/(?P<film_id>\d+)/', views.comment, name='comment'),
	re_path('movie/(?P<film_id>\d+)/', views.movie, name='movie'),

	path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('quit/', views.quit, name='quit'),
    path('person/', views.person, name='person')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

code/learning_logs/urls.py
"""定义learning_logs的URL模式"""

from django.urls import path, re_path


from . import views

# 命名空间
app_name = 'learning_logs'


# 注意path于re_path的用法区别
# path 用于不含参数方法的URL映射
# re_path 用于含参数方法的URL映射

urlpatterns = [
	# 显示所有的主题
	path('topics/', views.topics, name='topics'),

	# 显示指定主题的细节
	re_path('topic/(?P<topic_id>\d+)/', views.topic, name='topic'),

	# 用于添加新主题的网页
	path('new_topic/', views.new_topic, name='new_topic'),

	# 用于添加新条目的页面
	re_path('new_entry/(?P<topic_id>\d+)/', views.new_entry, name='new_entry'),

	# 用于编辑条目的页面
	re_path('edit_entry/(?P<entry_id>\d+)/', views.edit_entry, name='edit_entry'),
]

code/selfsearching/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('admin_app.urls', namespace='admin_app')),
    path('', include('users.urls', namespace='users')),
    path('', include('learning_logs.urls', namespace='learning_logs')),
    path('', include('small_tools.urls', namespace='small_tools')),
    path('', include('imagination.urls', namespace='imagination')),
    path('', include('films.urls', namespace='films')),
]

code/learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Topic(models.Model):
	"""用户学习的主题"""
	text = models.CharField(max_length=200)
	date_added = models.DateTimeField(auto_now_add=True)
	owner = models.ForeignKey(
		User, # 这里应该是 User, 而不是 'User', 否则会报错
		on_delete=models.CASCADE,
	)
	
	def __str__(self):
		"""返回模型的字符串表示"""
		return self.text
		
		
#Entry
class Entry(models.Model):
	"""学到的有关某个主题的具体知识"""
	topic = models.ForeignKey(Topic, on_delete=models.CASCADE,)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)
	
	class Meta:
		verbose_name_plural = 'entries'
		
	def __str__(self):
		"""返回模型的字符串表示"""
		return self.text[:50] + "..."

code/learning_logs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
	class Meta:
		model = Topic
		fields = ['text']
		labels = {'text': ''}


class EntryForm(forms.ModelForm):
	class Meta:
		model = Entry
		fields = ['text']
		labels = {'text': ''}
		widgets = {'text': forms.Textarea(attrs={'cols': 80})}

code/learning_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Topic
from .forms import TopicForm, EntryForm, Entry

# Create your views here.

# render()：用数据渲染Html文件
# reverse()：反向解析，从html文件名反向解析到url


# @login_required -- 注释掉该修饰器，否则用户未登录时不能进行跳转
def topics(request):
	"""显示所有的主题"""
	if request.user.is_authenticated:
		# 从数据库中查找某用户的所有主题，并按添加日期降序排列
		topics = Topic.objects.filter(owner=request.user).order_by('date_added')
		context = {'topics': topics}
		return render(request, 'learning_logs/topics.html', context)
	else:
		return render(request, 'users/login.html')


@login_required
def topic(request, topic_id):
	"""显示单个主题及其所有的条目"""
	topic = Topic.objects.get(id=topic_id)
	# 确认请求的主题是否属于当前用户
	if topic.owner != request.user:
		return Http404

	# '-'表示降序排列
	entries = topic.entry_set.order_by('-date_added')
	context = {'topic':topic, 'entries':entries}
	return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic(request):
	"""添加新主题"""
	if request.method != 'POST':
		# 未完成提交：创建一个新表单
		form = TopicForm()
	else:
		# POST提交的数据，对数据进行处理
		form = TopicForm(request.POST)
		if form.is_valid():
			new_topic = form.save(commit=False)
			new_topic.owner = request.user
			new_topic.save()
			return HttpResponseRedirect(reverse('learning_logs:topics'))
			
	context = {'form': form}
	return render(request, 'learning_logs/new_topic.html', context)
			
		
@login_required			
def new_entry(request, topic_id):
	"""在特定的主题中添加新的条目"""
	topic = Topic.objects.get(id=topic_id)
	
	if request.method != 'POST':
		# 未提交数据，创建一个新的表单
		form = EntryForm()
	else:
		# POST提交的数据，对数据进行处理
		form = EntryForm(data=request.POST)
		if form.is_valid():
			new_entry = form.save(commit=False)
			new_entry.topic = topic
			new_entry.save()
			return HttpResponseRedirect(reverse('learning_logs:topic',
												args=[topic_id]))
	
	context = {'topic': topic, 'form': form}
	return render(request, 'learning_logs/new_entry.html', context)
	

@login_required	
def edit_entry(request, entry_id):
	"""编辑既有条目"""
	entry = Entry.objects.get(id=entry_id)
	topic = entry.topic
	# 判断当前用户是否为该主题的所有者
	if topic.owner != request.user:
		return Http404
		
	if request.method != 'POST':
		# 初次请求，使用当前条目填充表单
		form = EntryForm(instance=entry)
	else:
		# POST提交的数据，对数据进行处理
		form = EntryForm(instance=entry, data=request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('learning_logs:topic',
												args=[topic.id]))
												
	context = {'entry': entry, 'topic': topic, 'form': form}
	return render(request, 'learning_logs/edit_entry.html',context)

code/learning_logs/templates/learning_logs/edit_entry.html
{% extends 'admin_app/base.html' %}

{% block content %}

	<a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
	
	<p>Edit Entry:</p>
	
	<form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">save changes</button>
	</form>

{% endblock content %}

code/learning_logs/templates/learning_logs/new_entry.html
{% extends 'admin_app/base.html' %}

{% block content %}

	<a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
	
	<p>Add a new Entry:</p>
	
	<form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">add entry</button>
	</form>

{% endblock content %}

code/learning_logs/templates/learning_logs/new_topic.html
{% extends 'admin_app/base.html' %}

{% block header %}
	<h2>Add a new topic:</h2>
{% endblock header %}

{% block content %}
	
	<form action="{% url 'learning_logs:new_topic' %}" method='post' class='form'>
		{% csrf_token %}
		{{ form.as_p }}
		
		<button name="submit" class="btn btn-primary">add topic</button>

	</form>
	
{% endblock content %}

code/learning_logs/templates/learning_logs/topic.html
{% extends 'admin_app/base.html' %}

{% block header %}
	<h2>{{ topic }}</h2>
{% endblock header %}

{% block content %}
	<p>
		<a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
	</p>
	
	{% for entry in entries %}
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3>
					{{ entry.date_added|date:'M d, Y H:i' }}
					<small>
						<a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a>
					</small>
				</h3>
			</div>
			
			<div class="panel-body">
				<p>{{ entry.text|linebreaks }}</p>
			</div>
		</div>
	{% empty %}
		<li>
			There are no entries for this topic yet.
		</li>
	{% endfor %}
	
{% endblock content %}

code/learning_logs/templates/learning_logs/topics.html
{% extends "admin_app/base.html" %}

{% block header %}
	<h2>
		Topics
		<a href="{% url 'learning_logs:new_topic' %}">+</a>
	</h2>
{% endblock header %}

{% block content %}
	
	<ul>
		{% for topic in topics %}
			<li>
				<h3>
					<p>
						<a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
						<a href="{% url 'learning_logs:new_topic' %}">+</a>
					</p>
				</h3>
			</li>
		{% empty %}
			<li>
				No topics have been added yet.
				<a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a>
			</li>
		{% endfor %}
	</ul>
	

	
{% endblock content %}