code/films/urls.py
"""定义learning_logs的URL模式"""

from django.urls import path, re_path
from django.conf.urls.static import static
from django.conf import settings

from . import views


# 命名空间
app_name = 'films'


# 注意path于re_path的用法区别
# path 用于不含参数方法的URL映射
# re_path 用于含参数方法的URL映射

urlpatterns = [
	# 显示所有的主题
	path('index/', views.index, name='index'),

	path('like/', views.like, name='like'),

	re_path('single/(?P<film_id>\d+)/', views.single, name='single'),
	re_path('comment/(?P<film_id>\d+)/', views.comment, name='comment'),
	re_path('movie/(?P<film_id>\d+)/', views.movie, name='movie'),

	path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('quit/', views.quit, name='quit'),
    path('person/', views.person, name='person')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

code/imagination/urls.py
"""定义learning_logs的URL模式"""

from django.urls import path, re_path
# from django.views.decorators.csrf import csrf_exempt

from . import views

# 命名空间
app_name = 'imagination'


# 注意path于re_path的用法区别
# path 用于不含参数方法的URL映射
# re_path 用于含参数方法的URL映射

urlpatterns = [
    # 小工具首页
	path('showIndex/', views.showIndex, name='showIndex'),
	# 学校入口页面
	path('collegeEntry/', views.collegeEntry, name='collegeEntry'),
	# 学校信息页面
	path('collegeInfo/', views.collegeInfo, name='collegeInfo'),
	path('academyInfo/', views.academyInfo, name='academyInfo'),
	path('majorInfo/', views.majorInfo, name='majorInfo'),
	path('gradeInfo/', views.gradeInfo, name='gradeInfo'),
	path('classInfo/', views.classInfo, name='classInfo'),
	re_path('studentInfo/(?P<student_id>\d+)/', views.studentInfo, name='studentInfo'),
	re_path('teacherInfo/(?P<teacher_id>\d+)/', views.teacherInfo, name='teacherInfo'),
]

code/selfsearching/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('admin_app.urls', namespace='admin_app')),
    path('', include('users.urls', namespace='users')),
    path('', include('learning_logs.urls', namespace='learning_logs')),
    path('', include('small_tools.urls', namespace='small_tools')),
    path('', include('imagination.urls', namespace='imagination')),
    path('', include('films.urls', namespace='films')),
]

code/small_tools/urls.py
"""定义learning_logs的URL模式"""

from django.urls import path, re_path
from django.views.decorators.csrf import csrf_exempt

from . import views

# 命名空间
app_name = 'small_tools'


# 注意path于re_path的用法区别
# path 用于不含参数方法的URL映射
# re_path 用于含参数方法的URL映射

urlpatterns = [
    # 小工具首页
	path('showTools/', views.showTools, name='showTools'),

    # snmp mib代码自动生成工具
	path('mibToCode/', views.mibToCode, name='mibToCode'),

	# 字符串处理算法页面
	path('algoString/', views.algoString, name='algoString'),

	# 正则表达式学习页面
	path('algoRegix/', csrf_exempt(views.algoRegix), name='algoRegix'),
]

code/imagination/forms.py
from django import forms
from django.forms import widgets

# from .collegeInfo.imTypes import CollegeEnum, AcademyEnum


# Form 仅做表单数据验证
# ModelForm 做数据库与表单数据验证

# class CollegeForm(forms.ModelForm):
#     """大学表单"""
#     class Meta:
#         # 表单对应的模型
#         model = CollegeInfo
#         # 引入的模型的属性
#         fields = ['name', 'collegeId', 'address', 'level', 'area', 'academyNum']
#         # 配置上述属性的html属性
#         # widgets = {'text': forms.Textarea(attrs={'cols': 80})}
#         widgets = {
#             'name': forms.TextInput(attrs={'class': "form-control",
#                                            'id': "collegeName",
#                                            'readonly': 'true',
#                                            'style': 'background:#FFFFFF; color:#000000; font-size:11pt',
#                                            'placeholder': '学校名称',
#                                            }),
#
#             'collegeId': forms.TextInput(attrs={'class': "form-control",
#                                                    'id': "collegeId",
#                                                    'readonly': 'true',
#                                                    'style': 'background:#FFFFFF; color:#000000; font-size:11pt',
#                                                    'placeholder': '学校编号',
#                                                    }),
#
#             'address': forms.TextInput(attrs={'class': "form-control",
#                                               'id': "address",
#                                               'readonly': 'true',
#                                               'style': 'background:#FFFFFF; color:#000000; font-size:11pt',
#                                               'placeholder': '学校地址',
#                                               }),
#
#             'level': forms.TextInput(attrs={'class': "form-control",
#                                             'id': "level",
#                                             'readonly': 'true',
#                                             'choice': COLLEGE_LEVELS,
#                                             'style': 'background:#FFFFFF; color:#000000; font-size:11pt',
#                                             'placeholder': '学校等级',
#                                             }),
#
#             'area': forms.TextInput(attrs={'class': "form-control",
#                                               'id': "area",
#                                               'readonly': 'true',
#                                               'style': 'background:#FFFFFF; color:#000000; font-size:11pt',
#                                               'placeholder': '学校面积',
#                                               }),
#
#             'academyNum': forms.TextInput(attrs={'class': "form-control",
#                                                     'id': "academyNum",
#                                                     'readonly': 'true',
#                                                     'style': 'background:#FFFFFF; color:#000000; font-size:11pt',
#                                                     'placeholder': '学院数量',
#                                                     }),
#         }
#
#

    # collegeName = forms.CharField(min_length = 10,
    #                            strip = True,
    #                            error_messages = {
    #                                'required':'该字段不能为空',
    #                                'min_length':'字符串长度不能小于1'
    #                            },
    #                            widget = widgets.Textarea(attrs={
    #                                'class':'form-control',
    #                                'id':'strInput',
    #                                'rows':'6',
    #                                'style':'background:#FFFFFF; color:#000000; font-size:11pt',
    #                                'placeholder':'请输入一个字符串',
    #                            }))
    # strOutput = forms.CharField(min_length = 1,
    #                            strip = True,
    #                            error_messages = None,
    #                            widget = widgets.Textarea(attrs={
    #                                'class':'form-control',
    #                                'id':'strOutput',
    #                                'rows':'6',
    #                                'style':'background:#DCDCDC; color:#000000; font-size:11pt',
    #                                'placeholder':'等待计算结果',
    #                                'readonly':'true'
    #                            }))



class CollegeEntryForm(forms.Form):
    """大学表单"""
    college_name = forms.ChoiceField(label='选择学校',
                                     widget=widgets.Select(attrs={
                                         'class': 'form-control',
                                         'id': 'college_name',
                                         'style': 'background:#FFFFFF; color:#000000; font-size:11pt',
                                         #  'placeholder':'请输入学校名字',
                                         })
                                     )

    def __init__(self, *args, **kwargs):
        # 实时更新，拷贝所有的静态字段，复制给self.fields
        super(CollegeEntryForm, self).__init__(*args, **kwargs)
        # choice_list = []
        # for item in CollegeEnum:
        #     choice_list.append([item.value, item.name])
        # self.fields['collegeName'].widget.choices = choice_list

    def collegeChoiceSet(self, choice_list):
        self.fields['college_name'].widget.choices = choice_list


class CollegeForm(forms.Form):
    """大学表单"""
    academy_name = forms.ChoiceField(label = '选择学院',
                                     widget=widgets.Select(attrs={
                                         'class': 'form-control',
                                         'id': 'academy_name',
                                         'style': 'background:#FFFFFF; color:#000000; font-size:11pt',
                                         #  'placeholder':'请输入学校名字',
                                         })
                                     )

    def __init__(self, *args, **kwargs):
        # 实时更新，拷贝所有的静态字段，复制给self.fields
        super(CollegeForm, self).__init__(*args, **kwargs)
        # choice_list = []
        # for item in AcademyEnum:
        #     choice_list.append([item.value, item.name])
        # self.fields['academyName'].widget.choices = choice_list

    def academyChoiceSet(self, choice_list):
        self.fields['academy_name'].widget.choices = choice_list


class AcademyForm(forms.Form):
    """学院表单"""
    major_name = forms.ChoiceField(label='选择专业',
                                   widget=widgets.Select(attrs={
                                       'class': 'form-control',
                                       'id': 'major_name',
                                       'style': 'background:#FFFFFF; color:#000000; font-size:11pt',
                                       #  'placeholder':'请输入学校名字',
                                       })
                                   )

    def majorChoiceSet(self, choice_list):
        self.fields['major_name'].widget.choices = choice_list


class MajorForm(forms.Form):
    """专业表单"""
    grade_id = forms.ChoiceField(label='选择年级',
                                 widget=widgets.Select(attrs={
                                     'class': 'form-control',
                                     'id': 'grade_id',
                                     'style': 'background:#FFFFFF; color:#000000; font-size:11pt',
                                     #  'placeholder':'请输入学校名字',
                                     })
                                 )

    def gradeChoiceSet(self, choice_list):
        self.fields['grade_id'].widget.choices = choice_list


class GradeForm(forms.Form):
    """年级表单"""
    class_id = forms.ChoiceField(label='选择班级',
                                 widget=widgets.Select(attrs={
                                     'class': 'form-control',
                                     'id': 'class_id',
                                     'style': 'background:#FFFFFF; color:#000000; font-size:11pt',
                                     #  'placeholder':'请输入学校名字',
                                     })
                                 )

    def classChoiceSet(self, choice_list):
        self.fields['class_id'].widget.choices = choice_list


class ClassForm(forms.Form):
    """班级表单"""
    student_name = forms.CharField(min_length = 1,
                                   strip = True,
                                   error_messages = None,
                                   widget = widgets.TextInput(attrs={
                                       'class': 'form-control',
                                       'id': 'student_name',
                                       'rows': '6',
                                       'style': 'background:#DCDCDC; color:#000000; font-size:11pt',
                                       'placeholder': '-',
                                       'readonly': 'true'
                                   }))
    student_id = forms.CharField(min_length=1,
                                 strip=True,
                                 error_messages=None,
                                 widget=widgets.TextInput(attrs={
                                     'class': 'form-control',
                                     'id': 'student_id',
                                     'rows': '6',
                                     'style': 'background:#DCDCDC; color:#000000; font-size:11pt',
                                     'placeholder': '-',
                                     'readonly': 'true'
                                 }))
    student_sex = forms.CharField(min_length=1,
                                  strip=True,
                                  error_messages=None,

code/imagination/views.py
from django.shortcuts import render

from .forms import CollegeEntryForm, CollegeForm, AcademyForm, MajorForm, GradeForm, ClassForm
from .collegeInfo.run import get_all_colleges_info, get_college_info, get_academy_info,\
    get_major_info, get_grade_info, get_class_info, get_teacher_info, get_student_info

# Create your views here.

def showIndex(request):
    return render(request, 'imagination/showIndex.html')


def collegeEntry(request):
    collegeEntryForm = CollegeEntryForm()
    # 生成学校信息列表，添加到学校选项中
    choice_list = []
    colleges_info = get_all_colleges_info()
    for college_name in colleges_info['colleges_name']:
        choice_list.append([college_name, college_name])
    collegeEntryForm.collegeChoiceSet(choice_list)
    return render(request, 'imagination/collegeEntry.html', {'collegeEntryForm': collegeEntryForm})


def collegeInfo(request):
    collegeForm = CollegeForm()
    choice_list = []
    college_name = ''

    if request.method == 'POST':
        college_name = request.POST['college_name']

    college_info = get_college_info(college_name)
    for academy_name in college_info['academies_name']:
        choice_list.append([academy_name, academy_name])
    collegeForm.academyChoiceSet(choice_list)
    return render(request, 'imagination/collegeInfo.html', {'collegeForm': collegeForm, 'college': college_info})


def academyInfo(request):
    academyForm = AcademyForm()
    choice_list = []
    academy_name = ''

    if request.method == 'POST':
        academy_name = request.POST['academy_name']

    academy_info = get_academy_info(academy_name)
    for major_name in academy_info['majors_name']:
        choice_list.append([major_name, major_name])
    academyForm.majorChoiceSet(choice_list)

    context = {'academyForm': academyForm, 'academy': academy_info}
    return render(request, 'imagination/academyInfo.html', context)


def majorInfo(request):
    majorForm = MajorForm()
    choice_list = []
    major_name = ''

    if request.method == 'POST':
        major_name = request.POST['major_name']

    major_info = get_major_info(major_name)
    for grade_id in range(1, major_info['grades_num'] + 1):
        choice_list.append([grade_id, grade_id])
    majorForm.gradeChoiceSet(choice_list)
    context = {'majorForm': majorForm, 'major': major_info}
    return render(request, 'imagination/majorInfo.html', context)


def gradeInfo(request):
    gradeForm = GradeForm()
    choice_list = []
    grade_id = 0

    if request.method == 'POST':
        grade_id = int(request.POST['grade_id'])

    grade_info = get_grade_info(grade_id)
    for class_id in range(1, grade_info['classes_num'] + 1):
        choice_list.append([class_id, class_id])
    gradeForm.classChoiceSet(choice_list)

    context = {'gradeForm': gradeForm, 'grade': grade_info}
    return render(request, 'imagination/gradeInfo.html', context)


def classInfo(request):
    class_id = 0
    if request.method == 'POST':
        class_id = int(request.POST['class_id'])
    class_info = get_class_info(class_id)
    context = {'classs': class_info}
    return render(request, 'imagination/classInfo.html', context)


# @login_required
def studentInfo(request, student_id):
    student_info = get_student_info(int(student_id))
    context = {'student': student_info}
    return render(request, 'imagination/studentInfo.html', context)


def teacherInfo(request, teacher_id):
    teacher_info = get_student_info(teacher_id)
    context = {'teacher': teacher_info}
    return render(request, 'imagination/classInfo.html', context)

code/imagination/templates/imagination/academyInfo.html
{% extends "admin_app/base.html" %}

{% block header %}
	<h2>
		<a href="{% url 'imagination:collegeInfo' %}">{{ academy.college_name }}</a>
		<small>
			>> {{ academy.name }}
		</small>
	</h2>
{% endblock header %}

{% block content %}

	<table border="1" class="table table-striped table-hover table-condensed">
		<tr>
			<th colspan="2">学院信息</th>
		</tr>
		<tr>
			<td>编号</td>
			<td>{{ academy.id }}</td>
		</tr>
		<tr>
			<td>简介</td>
			<td>{{ academy.description }}</td>
		</tr>
		<tr>
			<td>专业数量</td>
			<td>{{ academy.majors_num }}</td>
		</tr>
	</table>

	<form action="{% url 'imagination:majorInfo' %}" method='post' class='form'>
		{% csrf_token %}

		<table>
			{{ academyForm.as_table }}
		</table>

		<button name="submit" class="btn btn-primary">进入专业</button>

	</form>
	
{% endblock content %}

code/imagination/templates/imagination/classInfo.html
{% extends "admin_app/base.html" %}

{% block header %}
	<h2>
		<a href="{% url 'imagination:collegeInfo' %}">{{ classs.college_name }}</a>
		<small>
			>> <a href="{% url 'imagination:academyInfo' %}">{{ classs.academy_name }}</a>
			>> <a href="{% url 'imagination:majorInfo' %}">{{ classs.major_name }}</a>
			>> <a href="{% url 'imagination:gradeInfo' %}">{{ classs.grade_id }}年级</a>
			>> {{ classs.id }}班
		</small>
	</h2>
{% endblock header %}

{% block content %}

	<table border="1" class="table table-striped table-hover table-condensed">
		<tr>
			<th colspan="2">班级信息</th>
		</tr>
		<tr>
			<td>学生数量</td>
			<td>{{ classs.students_num }}</td>
		</tr>
	</table>

	<table border="1" class="table table-striped table-hover table-condensed">
		<tr>
			<th colspan="1">姓名</th>
			<th colspan="1">学号</th>
			<th colspan="1">性别</th>
		</tr>
		{% for student_info in classs.students_info %}
			<tr>
				<td><a href="{% url 'imagination:studentInfo' student_info.1 %}">{{ student_info.0 }}</a></td>
				<td>{{ student_info.1 }}</td>
				<td>{{ student_info.2 }}</td>
			</tr>
		{% empty %}
		{% endfor %}

	</table>
	
{% endblock content %}

code/imagination/templates/imagination/collegeEntry.html
{% extends "admin_app/base.html" %}

{% block header %}
	<h2>学校入口</h2>
{% endblock header %}

{% block content %}

	<form action="{% url 'imagination:collegeInfo' %}" method='post' class='form'>
		{% csrf_token %}
		{{ collegeEntryForm.as_p }}

		<button name="submit" class="btn btn-primary">进入学校</button>

	</form>
	
{% endblock content %}

code/imagination/templates/imagination/collegeInfo.html
{% extends "admin_app/base.html" %}

{% block header %}
	<h2>{{ college.name }}</h2>
{% endblock header %}

{% block content %}

	<table border="1" class="table table-striped table-hover table-condensed">
		<tr>
			<th colspan="2">学校信息</th>
		</tr>
		<tr>
			<td>编号</td>
			<td>{{ college.id }}</td>
		</tr>
		<tr>
			<td>简介</td>
			<td>{{ college.description }}</td>
		</tr>
		<tr>
			<td>地址</td>
			<td>{{ college.address }}</td>
		</tr>
		<tr>
			<td>级别</td>
			<td colspan="2">{{ college.level }}</td>
		</tr>
		<tr>
			 <td>面积</td>
			 <td>{{ college.area }}</td>
		</tr>
		<tr>
			 <td>校长</td>
			 <td>{{ college.headmaster_name }}</td>
		</tr>
		<tr>
			 <td>建校时间</td>
			 <td>{{ college.birthday }}</td>
		</tr>
		<tr>
			 <td>学院数量</td>
			 <td>{{ college.academies_num }}</td>
		</tr>
		<tr>
			 <td>专业数量</td>
			 <td>{{ college.majors_num }}</td>
		</tr>
		<tr>
			 <td>教师数量</td>
			 <td>{{ college.teachers_num }}</td>
		</tr>
		<tr>
			 <td>学生数量</td>
			 <td>{{ college.students_num }}</td>
		</tr>
	</table>

	<form action="{% url 'imagination:academyInfo' %}" method='post' class='form'>
		{% csrf_token %}

		<table>
			{{ collegeForm.as_table }}
		</table>

		<button name="submit" class="btn btn-primary">进入学院</button>

	</form>
	
{% endblock content %}

code/imagination/templates/imagination/gradeInfo.html
{% extends "admin_app/base.html" %}

{% block header %}
	<h2>
		<a href="{% url 'imagination:collegeInfo' %}">{{ grade.college_name }}</a>
		<small>
			>> <a href="{% url 'imagination:academyInfo' %}">{{ grade.academy_name }}</a>
			>> <a href="{% url 'imagination:majorInfo' %}">{{ grade.major_name }}</a>
			>> {{ grade.id }}年级
		</small>
	</h2>
{% endblock header %}

{% block content %}

	<table border="1" class="table table-striped table-hover table-condensed">
		<tr>
			<th colspan="2">年级信息</th>
		</tr>
		<tr>
			<td>班级数量</td>
			<td>{{ grade.classes_num }}</td>
		</tr>
		<tr>
			<td>学生数量</td>
			<td>{{ grade.students_num }}</td>
		</tr>
	</table>

	<form action="{% url 'imagination:classInfo' %}" method='post' class='form'>
		{% csrf_token %}

		<table>
			{{ gradeForm.as_table }}
		</table>

		<button name="submit" class="btn btn-primary">进入班级</button>

	</form>
	
{% endblock content %}

code/imagination/templates/imagination/inputCollegeInfo.html
{% extends "admin_app/base.html" %}

{% block header %}
	<h2>Small tools</h2>
{% endblock header %}

{% block content %}
	
	<ul>
		<li>
			<h3>
				<a href="{% url 'small_tools:mibToCode' %}">Snmp mib代码生成工具</a>
			</h3>
		</li>
		<li>
			<h3>
				<a href="{% url 'small_tools:algoString' %}">字符串处理工具</a>
			</h3>
		</li>
		<li>
			<h3>
				<a href="{% url 'small_tools:algoRegix' %}">正则表达式学习工具</a>
			</h3>
		</li>
	</ul>
	
{% endblock content %}

code/imagination/templates/imagination/majorInfo.html
{% extends "admin_app/base.html" %}

{% block header %}
	<h2>
		<a href="{% url 'imagination:collegeInfo' %}">{{ major.college_name }}</a>
		<small>
			>> <a href="{% url 'imagination:academyInfo' %}">{{ major.academy_name }}</a>
			>> {{ major.name }}
		</small>
	</h2>
{% endblock header %}

{% block content %}

	<table border="1" class="table table-striped table-hover table-condensed">
		<tr>
			<th colspan="2">专业信息</th>
		</tr>
		<tr>
			<td>编号</td>
			<td>{{ major.id }}</td>
		</tr>
		<tr>
			<td>年级数量</td>
			<td>{{ major.grades_num }}</td>
		</tr>
		<tr>
			<td>教师数量</td>
			<td>{{ major.teachers_num }}</td>
		</tr>
		<tr>
			<td>学生数量</td>
			<td>{{ major.students_num }}</td>
		</tr>
	</table>

	<form action="{% url 'imagination:gradeInfo' %}" method='post' class='form'>
		{% csrf_token %}

		<table>
			{{ majorForm.as_table }}
		</table>

		<button name="submit" class="btn btn-primary">进入年级</button>

	</form>
	
{% endblock content %}

code/imagination/templates/imagination/showIndex.html
{% extends "admin_app/base.html" %}

{% block header %}
	<h2>Small tools</h2>
{% endblock header %}

{% block content %}
	
	<ul>
		<li>
			<h3>
				<a href="{% url 'imagination:collegeEntry' %}">学校信息</a>
			</h3>
		</li>
		<li>
			<h3>
				<a href="{% url 'small_tools:algoString' %}">字符串处理工具</a>
			</h3>
		</li>
		<li>
			<h3>
				<a href="{% url 'small_tools:algoRegix' %}">正则表达式学习工具</a>
			</h3>
		</li>
	</ul>
	
{% endblock content %}

code/imagination/templates/imagination/studentInfo.html
{% extends "admin_app/base.html" %}

{% block header %}
	<h2><a href="{% url 'imagination:collegeInfo' %}">{{ student.college_name }}</a>
		<small>
			>> <a href="{% url 'imagination:academyInfo' %}">{{ student.academy_name }}</a>
			>> <a href="{% url 'imagination:majorInfo' %}">{{ student.major_name }}</a>
			>> <a href="{% url 'imagination:gradeInfo' %}">{{ student.grade_id }}年级</a>
			>> <a href="{% url 'imagination:classInfo' %}">{{ student.class_id }}年级</a>
			>> {{ student.name }}
		</small>
	</h2>

{% endblock header %}

{% block content %}

	<table border="1" class="table table-striped table-hover table-condensed">
		<tr>
			<th colspan="2">学生信息</th>
		</tr>
		<tr>
			<td>学号</td>
			<td>{{ student.id }}</td>
		</tr>
		<tr>
			<td>姓名拼音</td>
			<td>{{ student.name_pinyin }}</td>
		</tr>
		<tr>
			<td>性别</td>
			<td>{{ student.sex }}</td>
		</tr>
		<tr>
			<td>年龄</td>
			<td>{{ student.age }}</td>
		</tr>
		<tr>
			<td>入学时间</td>
			<td>{{ student.year_in_college }}</td>
		</tr>
		<tr>
			<td>身高</td>
			<td>{{ student.height }}</td>
		</tr>
		<tr>
			<td>体重</td>
			<td>{{ student.weight }}</td>
		</tr>
		<tr>
			<td>身份证号</td>
			<td>{{ student.id_number }}</td>
		</tr>
		<tr>
			<td>爱好</td>
			<td>{{ student.hobbies }}</td>
		</tr>
		<tr>
			<td>胸围</td>
			<td>{{ student.bust }}</td>
		</tr>
		<tr>
			<td>腰围</td>
			<td>{{ student.waist }}</td>
		</tr>
		<tr>
			<td>臀围</td>
			<td>{{ student.hips }}</td>
		</tr>
		<tr>
			<td>婚姻状况</td>
			<td>{{ student.married }}</td>
		</tr>
	</table>

	<form action="{% url 'imagination:collegeInfo' %}" method='post' class='form'>
		{% csrf_token %}

		<table>
		</table>

		<button name="submit" class="btn btn-primary">进入学院</button>

	</form>
	
{% endblock content %}